# ------ Dataset ------
dataset: blender
batching: single_image
factor: 2
batch_size: 1024

# ------ NeRF ------
num_coarse_samples: 64
num_fine_samples: 128
use_viewdirs: true
white_bkgd: false
use_pixel_centers: true
randomized: true

# ------ Training ------
lr_delay_mult: 0.01
# lr_delay_steps: 300
# max_steps: 30000
lr_delay_steps: 2500
max_steps: 200000
# precrop_iters: 500
# precrop_frac: 0.5

# ------ Evaluation ------
render_every: 10000
save_every: 10000

# ------ SH encoding ------
sh_deg: -1
sh_direnc_deg: -1

# ------ Path sampling ------
num_path_samples: 12

# ------ Extra dataset/loss/smooth ------
sparsity_weight: 0.0
use_online_sparsity: false
extra_batch_size: 16
use_fine_sparsity: false
normal_loss_weight: 0.0
normal_smooth_weight: 0.0
# anneal_delay_steps: 0
# anneal_max_steps: 2400
anneal_delay_steps: 2500
anneal_max_steps: 160000
beta_weight: 0.0
bg_weight: 0.025
bg_smooth_weight: 1.0
bg_patch_size: 128
